set_property PACKAGE_PIN U9 [get_ports v[0]]
set_property IOSTANDARD LVCMOS33 [get_ports v[0]]
set_property PACKAGE_PIN U8 [get_ports v[1]]
set_property IOSTANDARD LVCMOS33 [get_ports v[1]]
set_property PACKAGE_PIN R7 [get_ports v[2]]
set_property IOSTANDARD LVCMOS33 [get_ports v[2]]
set_property PACKAGE_PIN R6 [get_ports v[3]]
set_property IOSTANDARD LVCMOS33 [get_ports v[3]]

set_property PACKAGE_PIN F15 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN T8 [get_ports locked]
set_property IOSTANDARD LVCMOS33 [get_ports locked]

set_property PACKAGE_PIN E3 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in]

create_clock -period 10.000 -name Clk -waveform {0.000 5.000} [get_ports {clk_in}]

set_property PACKAGE_PIN N6 [get_ports an[0]]
set_property IOSTANDARD LVCMOS33 [get_ports an[0]]
set_property PACKAGE_PIN M6 [get_ports an[1]]
set_property IOSTANDARD LVCMOS33 [get_ports an[1]]
set_property PACKAGE_PIN M3 [get_ports an[2]]
set_property IOSTANDARD LVCMOS33 [get_ports an[2]]
set_property PACKAGE_PIN N5 [get_ports an[3]]
set_property IOSTANDARD LVCMOS33 [get_ports an[3]]

set_property PACKAGE_PIN N2 [get_ports an[4]]
set_property IOSTANDARD LVCMOS33 [get_ports an[4]]
set_property PACKAGE_PIN N4 [get_ports an[5]]
set_property IOSTANDARD LVCMOS33 [get_ports an[5]]
set_property PACKAGE_PIN L1 [get_ports an[6]]
set_property IOSTANDARD LVCMOS33 [get_ports an[6]]
set_property PACKAGE_PIN M1 [get_ports an[7]]
set_property IOSTANDARD LVCMOS33 [get_ports an[7]]

set_property PACKAGE_PIN L3 [get_ports seg[0]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[0]]
set_property PACKAGE_PIN N1 [get_ports seg[1]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[1]]
set_property PACKAGE_PIN L5 [get_ports seg[2]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[2]]
set_property PACKAGE_PIN L4 [get_ports seg[3]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[3]]
set_property PACKAGE_PIN K3 [get_ports seg[4]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[4]]
set_property PACKAGE_PIN M2 [get_ports seg[5]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[5]]
set_property PACKAGE_PIN L6 [get_ports seg[6]]
set_property IOSTANDARD LVCMOS33 [get_ports seg[6]]
