set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets <myHier/myNet>]
set_property PACKAGE_PIN U9 [get_ports d]
set_property IOSTANDARD LVCMOS33 [get_ports d]
set_property PACKAGE_PIN U8 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN R7 [get_ports ce]
set_property IOSTANDARD LVCMOS33 [get_ports ce]
set_property PACKAGE_PIN P4 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN T8 [get_ports q]
set_property IOSTANDARD LVCMOS33 [get_ports q]

