set_property PACKAGE_PIN J15 [get_ports x[0]]
set_property IOSTANDARD LVCMOS33 [get_ports x[0]]
set_property PACKAGE_PIN L16 [get_ports x[1]]
set_property IOSTANDARD LVCMOS33 [get_ports x[1]]
set_property PACKAGE_PIN M13 [get_ports x[2]]
set_property IOSTANDARD LVCMOS33 [get_ports x[2]]

set_property PACKAGE_PIN H17 [get_ports y[0]]
set_property IOSTANDARD LVCMOS33 [get_ports y[0]]
set_property PACKAGE_PIN K15 [get_ports y[1]]
set_property IOSTANDARD LVCMOS33 [get_ports y[1]]
set_property PACKAGE_PIN J13 [get_ports y[2]]
set_property IOSTANDARD LVCMOS33 [get_ports y[2]]
set_property PACKAGE_PIN N14 [get_ports y[3]]
set_property IOSTANDARD LVCMOS33 [get_ports y[3]]
set_property PACKAGE_PIN R18 [get_ports y[4]]
set_property IOSTANDARD LVCMOS33 [get_ports y[4]]
set_property PACKAGE_PIN V17 [get_ports y[5]]
set_property IOSTANDARD LVCMOS33 [get_ports y[5]]
set_property PACKAGE_PIN U17 [get_ports y[6]]
set_property IOSTANDARD LVCMOS33 [get_ports y[6]]
set_property PACKAGE_PIN U16 [get_ports y[7]]
set_property IOSTANDARD LVCMOS33 [get_ports y[7]]

