set_property PACKAGE_PIN J17 [get_ports an[0]]
set_property IOSTANDARD LVCMOS33 [get_ports an[0]]
set_property PACKAGE_PIN J18 [get_ports an[1]]
set_property IOSTANDARD LVCMOS33 [get_ports an[1]]
set_property PACKAGE_PIN T9 [get_ports an[2]]
set_property IOSTANDARD LVCMOS33 [get_ports an[2]]
set_property PACKAGE_PIN J14 [get_ports an[3]]
set_property IOSTANDARD LVCMOS33 [get_ports an[3]]

set_property PACKAGE_PIN P14 [get_ports an[4]]
set_property IOSTANDARD LVCMOS33 [get_ports an[4]]
set_property PACKAGE_PIN T14 [get_ports an[5]]
set_property IOSTANDARD LVCMOS33 [get_ports an[5]]
set_property PACKAGE_PIN K2 [get_ports an[6]]
set_property IOSTANDARD LVCMOS33 [get_ports an[6]]
set_property PACKAGE_PIN U13 [get_ports an[7]]
set_property IOSTANDARD LVCMOS33 [get_ports an[7]]

set_property PACKAGE_PIN T10 [get_ports seg0[0]]
set_property IOSTANDARD LVCMOS33 [get_ports seg0[0]]
set_property PACKAGE_PIN R10 [get_ports seg0[1]]
set_property IOSTANDARD LVCMOS33 [get_ports seg0[1]]
set_property PACKAGE_PIN K16 [get_ports seg0[2]]
set_property IOSTANDARD LVCMOS33 [get_ports seg0[2]]
set_property PACKAGE_PIN K13 [get_ports seg0[3]]
set_property IOSTANDARD LVCMOS33 [get_ports seg0[3]]
set_property PACKAGE_PIN P15 [get_ports seg0[4]]
set_property IOSTANDARD LVCMOS33 [get_ports seg0[4]]
set_property PACKAGE_PIN T11 [get_ports seg0[5]]
set_property IOSTANDARD LVCMOS33 [get_ports seg0[5]]
set_property PACKAGE_PIN L18 [get_ports seg0[6]]
set_property IOSTANDARD LVCMOS33 [get_ports seg0[6]]

set_property PACKAGE_PIN J15 [get_ports v[0]]
set_property IOSTANDARD LVCMOS33 [get_ports v[0]]
set_property PACKAGE_PIN L16 [get_ports v[1]]
set_property IOSTANDARD LVCMOS33 [get_ports v[1]]
set_property PACKAGE_PIN M13 [get_ports v[2]]
set_property IOSTANDARD LVCMOS33 [get_ports v[2]]
set_property PACKAGE_PIN R15 [get_ports v[3]]
set_property IOSTANDARD LVCMOS33 [get_ports v[3]]

set_property PACKAGE_PIN H17 [get_ports z]
set_property IOSTANDARD LVCMOS33 [get_ports z]
