set_property PACKAGE_PIN U9 [get_ports d[0]]
set_property IOSTANDARD LVCMOS33 [get_ports d[0]]
set_property PACKAGE_PIN U8 [get_ports d[1]]
set_property IOSTANDARD LVCMOS33 [get_ports d[1]]
set_property PACKAGE_PIN R7 [get_ports d[2]]
set_property IOSTANDARD LVCMOS33 [get_ports d[2]]
set_property PACKAGE_PIN R6 [get_ports d[3]]
set_property IOSTANDARD LVCMOS33 [get_ports d[3]]
set_property PACKAGE_PIN R5 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN V7 [get_ports set]
set_property IOSTANDARD LVCMOS33 [get_ports set]
set_property PACKAGE_PIN V6 [get_ports load]
set_property IOSTANDARD LVCMOS33 [get_ports load]

set_property PACKAGE_PIN P4 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

set_property PACKAGE_PIN T8 [get_ports q[0]]
set_property IOSTANDARD LVCMOS33 [get_ports q[0]]
set_property PACKAGE_PIN V9 [get_ports q[1]]
set_property IOSTANDARD LVCMOS33 [get_ports q[1]]
set_property PACKAGE_PIN R8 [get_ports q[2]]
set_property IOSTANDARD LVCMOS33 [get_ports q[2]]
set_property PACKAGE_PIN T6 [get_ports q[3]]
set_property IOSTANDARD LVCMOS33 [get_ports q[3]]

